<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8" /><meta name="generator" content="Docutils 0.17.1: http://docutils.sourceforge.net/" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>14.8 创建自定义异常 &mdash; python3-cookbook 3.0.0 documentation</title>
      <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="../_static/css/theme.css" type="text/css" />
  <!--[if lt IE 9]>
    <script src="../_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
        <script data-url_root="../" id="documentation_options" src="../_static/documentation_options.js"></script>
        <script src="../_static/jquery.js"></script>
        <script src="../_static/underscore.js"></script>
        <script src="../_static/_sphinx_javascript_frameworks_compat.js"></script>
        <script src="../_static/doctools.js"></script>
        <script src="../_static/sphinx_highlight.js"></script>
    <script src="../_static/js/theme.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
    <link rel="copyright" title="Copyright" href="../copyright.html" />
    <link rel="next" title="14.9 捕获异常后抛出另外的异常" href="p09_raise_exception_in_response_to_another_exception.html" />
    <link rel="prev" title="14.7 捕获所有异常" href="p07_catching_all_exceptions.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
            <a href="../index.html" class="icon icon-home"> python3-cookbook
          </a>
              <div class="version">
                3.0
              </div>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <ul class="current">
<li class="toctree-l1"><a class="reference internal" href="../copyright.html">Copyright</a></li>
<li class="toctree-l1"><a class="reference internal" href="../preface.html">前言</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p01_data_structures_algorithms.html">第一章：数据结构和算法</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p02_strings_and_text.html">第二章：字符串和文本</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p03_numbers_dates_times.html">第三章：数字日期和时间</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p04_iterators_and_generators.html">第四章：迭代器与生成器</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p05_files_and_io.html">第五章：文件与IO</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p06_data_encoding_and_process.html">第六章：数据编码和处理</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p07_functions.html">第七章：函数</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p08_classes_and_objects.html">第八章：类与对象</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p09_meta_programming.html">第九章：元编程</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p10_modules_and_packages.html">第十章：模块与包</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p11_network_and_web_program.html">第十一章：网络与Web编程</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p12_concurrency.html">第十二章：并发编程</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p13_utility_script_and_system_manage.html">第十三章：脚本编程与系统管理</a></li>
<li class="toctree-l1 current"><a class="reference internal" href="../chapters/p14_test_debug_and_exceptions.html">第十四章：测试、调试和异常</a><ul class="current">
<li class="toctree-l2"><a class="reference internal" href="p01_testing_output_sent_to_stdout.html">14.1 测试stdout输出</a></li>
<li class="toctree-l2"><a class="reference internal" href="p02_patching_objects_in_unit_tests.html">14.2 在单元测试中给对象打补丁</a></li>
<li class="toctree-l2"><a class="reference internal" href="p03_testing_for_exceptional_conditions_in_unit_tests.html">14.3 在单元测试中测试异常情况</a></li>
<li class="toctree-l2"><a class="reference internal" href="p04_logging_test_output_to_file.html">14.4 将测试输出用日志记录到文件中</a></li>
<li class="toctree-l2"><a class="reference internal" href="p05_skip_or_anticipate_test_failures.html">14.5 忽略或期望测试失败</a></li>
<li class="toctree-l2"><a class="reference internal" href="p06_handle_multiple_exceptions.html">14.6 处理多个异常</a></li>
<li class="toctree-l2"><a class="reference internal" href="p07_catching_all_exceptions.html">14.7 捕获所有异常</a></li>
<li class="toctree-l2 current"><a class="current reference internal" href="#">14.8 创建自定义异常</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id2">问题</a></li>
<li class="toctree-l3"><a class="reference internal" href="#id3">解决方案</a></li>
<li class="toctree-l3"><a class="reference internal" href="#id4">讨论</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="p09_raise_exception_in_response_to_another_exception.html">14.9 捕获异常后抛出另外的异常</a></li>
<li class="toctree-l2"><a class="reference internal" href="p10_reraising_the_last_exception.html">14.10 重新抛出被捕获的异常</a></li>
<li class="toctree-l2"><a class="reference internal" href="p11_issuing_warning_messages.html">14.11 输出警告信息</a></li>
<li class="toctree-l2"><a class="reference internal" href="p12_debugging_basic_program_crashes.html">14.12 调试基本的程序崩溃错误</a></li>
<li class="toctree-l2"><a class="reference internal" href="p13_profiling_and_timing_your_program.html">14.13 给你的程序做性能测试</a></li>
<li class="toctree-l2"><a class="reference internal" href="p14_make_your_program_run_faster.html">14.14 加速程序运行</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p15_c_extensions.html">第十五章：C语言扩展</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p16_appendix.html">附录A</a></li>
<li class="toctree-l1"><a class="reference internal" href="../aboutme.html">关于译者</a></li>
<li class="toctree-l1"><a class="reference internal" href="../roadmap.html">Roadmap</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../index.html">python3-cookbook</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="../index.html" class="icon icon-home"></a></li>
          <li class="breadcrumb-item"><a href="../chapters/p14_test_debug_and_exceptions.html">第十四章：测试、调试和异常</a></li>
      <li class="breadcrumb-item active">14.8 创建自定义异常</li>
      <li class="wy-breadcrumbs-aside">
            <a href="../_sources/c14/p08_creating_custom_exceptions.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <section id="id1">
<h1>14.8 创建自定义异常<a class="headerlink" href="#id1" title="Permalink to this heading">¶</a></h1>
<section id="id2">
<h2>问题<a class="headerlink" href="#id2" title="Permalink to this heading">¶</a></h2>
<p>在你构建的应用程序中，你想将底层异常包装成自定义的异常。</p>
</section>
<section id="id3">
<h2>解决方案<a class="headerlink" href="#id3" title="Permalink to this heading">¶</a></h2>
<p>创建新的异常很简单——定义新的类，让它继承自 <code class="docutils literal notranslate"><span class="pre">Exception</span></code> （或者是任何一个已存在的异常类型）。
例如，如果你编写网络相关的程序，你可能会定义一些类似如下的异常：</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">NetworkError</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
    <span class="k">pass</span>

<span class="k">class</span> <span class="nc">HostnameError</span><span class="p">(</span><span class="n">NetworkError</span><span class="p">):</span>
    <span class="k">pass</span>

<span class="k">class</span> <span class="nc">TimeoutError</span><span class="p">(</span><span class="n">NetworkError</span><span class="p">):</span>
    <span class="k">pass</span>

<span class="k">class</span> <span class="nc">ProtocolError</span><span class="p">(</span><span class="n">NetworkError</span><span class="p">):</span>
    <span class="k">pass</span>
</pre></div>
</div>
<p>然后用户就可以像通常那样使用这些异常了，例如：</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">msg</span> <span class="o">=</span> <span class="n">s</span><span class="o">.</span><span class="n">recv</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">TimeoutError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span> <span class="n">ProtocolError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="o">...</span>
</pre></div>
</div>
</section>
<section id="id4">
<h2>讨论<a class="headerlink" href="#id4" title="Permalink to this heading">¶</a></h2>
<p>自定义异常类应该总是继承自内置的 <code class="docutils literal notranslate"><span class="pre">Exception</span></code> 类，
或者是继承自那些本身就是从 <code class="docutils literal notranslate"><span class="pre">Exception</span></code> 继承而来的类。
尽管所有类同时也继承自 <code class="docutils literal notranslate"><span class="pre">BaseException</span></code> ，但你不应该使用这个基类来定义新的异常。
<code class="docutils literal notranslate"><span class="pre">BaseException</span></code> 是为系统退出异常而保留的，比如 <code class="docutils literal notranslate"><span class="pre">KeyboardInterrupt</span></code> 或 <code class="docutils literal notranslate"><span class="pre">SystemExit</span></code>
以及其他那些会给应用发送信号而退出的异常。
因此，捕获这些异常本身没什么意义。
这样的话，假如你继承 <code class="docutils literal notranslate"><span class="pre">BaseException</span></code>
可能会导致你的自定义异常不会被捕获而直接发送信号退出程序运行。</p>
<p>在程序中引入自定义异常可以使得你的代码更具可读性，能清晰显示谁应该阅读这个代码。
还有一种设计是将自定义异常通过继承组合起来。在复杂应用程序中，
使用基类来分组各种异常类也是很有用的。它可以让用户捕获一个范围很窄的特定异常，比如下面这样的：</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">s</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="n">msg</span><span class="p">)</span>
<span class="k">except</span> <span class="n">ProtocolError</span><span class="p">:</span>
    <span class="o">...</span>
</pre></div>
</div>
<p>你还能捕获更大范围的异常，就像下面这样：</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">s</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="n">msg</span><span class="p">)</span>
<span class="k">except</span> <span class="n">NetworkError</span><span class="p">:</span>
    <span class="o">...</span>
</pre></div>
</div>
<p>如果你想定义的新异常重写了 <code class="docutils literal notranslate"><span class="pre">__init__()</span></code> 方法，
确保你使用所有参数调用 <code class="docutils literal notranslate"><span class="pre">Exception.__init__()</span></code> ，例如：</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">CustomError</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">message</span><span class="p">,</span> <span class="n">status</span><span class="p">):</span>
        <span class="nb">super</span><span class="p">()</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="n">message</span><span class="p">,</span> <span class="n">status</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">message</span> <span class="o">=</span> <span class="n">message</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">status</span> <span class="o">=</span> <span class="n">status</span>
</pre></div>
</div>
<p>看上去有点奇怪，不过Exception的默认行为是接受所有传递的参数并将它们以元组形式存储在 <code class="docutils literal notranslate"><span class="pre">.args</span></code> 属性中.
很多其他函数库和部分Python库默认所有异常都必须有 <code class="docutils literal notranslate"><span class="pre">.args</span></code> 属性，
因此如果你忽略了这一步，你会发现有些时候你定义的新异常不会按照期望运行。
为了演示 <code class="docutils literal notranslate"><span class="pre">.args</span></code> 的使用，考虑下下面这个使用内置的 <cite>RuntimeError`</cite> 异常的交互会话，
注意看raise语句中使用的参数个数是怎样的：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s1">&#39;It failed&#39;</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span> <span class="ne">RuntimeError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="n">e</span><span class="o">.</span><span class="n">args</span><span class="p">)</span>
<span class="gp">...</span>
<span class="go">(&#39;It failed&#39;,)</span>
<span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>    <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s1">&#39;It failed&#39;</span><span class="p">,</span> <span class="mi">42</span><span class="p">,</span> <span class="s1">&#39;spam&#39;</span><span class="p">)</span>
<span class="gp">... </span><span class="k">except</span> <span class="ne">RuntimeError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>

<span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="n">e</span><span class="o">.</span><span class="n">args</span><span class="p">)</span>
<span class="gp">...</span>
<span class="go">(&#39;It failed&#39;, 42, &#39;spam&#39;)</span>
<span class="go">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>关于创建自定义异常的更多信息，请参考`Python官方文档 &lt;<a class="reference external" href="https://docs.python.org/3/tutorial/errors.html">https://docs.python.org/3/tutorial/errors.html</a>&gt;`_</p>
</section>
</section>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="Footer">
        <a href="p07_catching_all_exceptions.html" class="btn btn-neutral float-left" title="14.7 捕获所有异常" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
        <a href="p09_raise_exception_in_response_to_another_exception.html" class="btn btn-neutral float-right" title="14.9 捕获异常后抛出另外的异常" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; <a href="../copyright.html">Copyright</a> 2017, 熊能.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>