<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8" /><meta name="generator" content="Docutils 0.17.1: http://docutils.sourceforge.net/" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>14.9 捕获异常后抛出另外的异常 &mdash; python3-cookbook 3.0.0 documentation</title>
      <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="../_static/css/theme.css" type="text/css" />
  <!--[if lt IE 9]>
    <script src="../_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
        <script data-url_root="../" id="documentation_options" src="../_static/documentation_options.js"></script>
        <script src="../_static/jquery.js"></script>
        <script src="../_static/underscore.js"></script>
        <script src="../_static/_sphinx_javascript_frameworks_compat.js"></script>
        <script src="../_static/doctools.js"></script>
        <script src="../_static/sphinx_highlight.js"></script>
    <script src="../_static/js/theme.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
    <link rel="copyright" title="Copyright" href="../copyright.html" />
    <link rel="next" title="14.10 重新抛出被捕获的异常" href="p10_reraising_the_last_exception.html" />
    <link rel="prev" title="14.8 创建自定义异常" href="p08_creating_custom_exceptions.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
            <a href="../index.html" class="icon icon-home"> python3-cookbook
          </a>
              <div class="version">
                3.0
              </div>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <ul class="current">
<li class="toctree-l1"><a class="reference internal" href="../copyright.html">Copyright</a></li>
<li class="toctree-l1"><a class="reference internal" href="../preface.html">前言</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p01_data_structures_algorithms.html">第一章：数据结构和算法</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p02_strings_and_text.html">第二章：字符串和文本</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p03_numbers_dates_times.html">第三章：数字日期和时间</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p04_iterators_and_generators.html">第四章：迭代器与生成器</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p05_files_and_io.html">第五章：文件与IO</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p06_data_encoding_and_process.html">第六章：数据编码和处理</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p07_functions.html">第七章：函数</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p08_classes_and_objects.html">第八章：类与对象</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p09_meta_programming.html">第九章：元编程</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p10_modules_and_packages.html">第十章：模块与包</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p11_network_and_web_program.html">第十一章：网络与Web编程</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p12_concurrency.html">第十二章：并发编程</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p13_utility_script_and_system_manage.html">第十三章：脚本编程与系统管理</a></li>
<li class="toctree-l1 current"><a class="reference internal" href="../chapters/p14_test_debug_and_exceptions.html">第十四章：测试、调试和异常</a><ul class="current">
<li class="toctree-l2"><a class="reference internal" href="p01_testing_output_sent_to_stdout.html">14.1 测试stdout输出</a></li>
<li class="toctree-l2"><a class="reference internal" href="p02_patching_objects_in_unit_tests.html">14.2 在单元测试中给对象打补丁</a></li>
<li class="toctree-l2"><a class="reference internal" href="p03_testing_for_exceptional_conditions_in_unit_tests.html">14.3 在单元测试中测试异常情况</a></li>
<li class="toctree-l2"><a class="reference internal" href="p04_logging_test_output_to_file.html">14.4 将测试输出用日志记录到文件中</a></li>
<li class="toctree-l2"><a class="reference internal" href="p05_skip_or_anticipate_test_failures.html">14.5 忽略或期望测试失败</a></li>
<li class="toctree-l2"><a class="reference internal" href="p06_handle_multiple_exceptions.html">14.6 处理多个异常</a></li>
<li class="toctree-l2"><a class="reference internal" href="p07_catching_all_exceptions.html">14.7 捕获所有异常</a></li>
<li class="toctree-l2"><a class="reference internal" href="p08_creating_custom_exceptions.html">14.8 创建自定义异常</a></li>
<li class="toctree-l2 current"><a class="current reference internal" href="#">14.9 捕获异常后抛出另外的异常</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id2">问题</a></li>
<li class="toctree-l3"><a class="reference internal" href="#id3">解决方案</a></li>
<li class="toctree-l3"><a class="reference internal" href="#id4">讨论</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="p10_reraising_the_last_exception.html">14.10 重新抛出被捕获的异常</a></li>
<li class="toctree-l2"><a class="reference internal" href="p11_issuing_warning_messages.html">14.11 输出警告信息</a></li>
<li class="toctree-l2"><a class="reference internal" href="p12_debugging_basic_program_crashes.html">14.12 调试基本的程序崩溃错误</a></li>
<li class="toctree-l2"><a class="reference internal" href="p13_profiling_and_timing_your_program.html">14.13 给你的程序做性能测试</a></li>
<li class="toctree-l2"><a class="reference internal" href="p14_make_your_program_run_faster.html">14.14 加速程序运行</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p15_c_extensions.html">第十五章：C语言扩展</a></li>
<li class="toctree-l1"><a class="reference internal" href="../chapters/p16_appendix.html">附录A</a></li>
<li class="toctree-l1"><a class="reference internal" href="../aboutme.html">关于译者</a></li>
<li class="toctree-l1"><a class="reference internal" href="../roadmap.html">Roadmap</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../index.html">python3-cookbook</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="../index.html" class="icon icon-home"></a></li>
          <li class="breadcrumb-item"><a href="../chapters/p14_test_debug_and_exceptions.html">第十四章：测试、调试和异常</a></li>
      <li class="breadcrumb-item active">14.9 捕获异常后抛出另外的异常</li>
      <li class="wy-breadcrumbs-aside">
            <a href="../_sources/c14/p09_raise_exception_in_response_to_another_exception.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <section id="id1">
<h1>14.9 捕获异常后抛出另外的异常<a class="headerlink" href="#id1" title="Permalink to this heading">¶</a></h1>
<section id="id2">
<h2>问题<a class="headerlink" href="#id2" title="Permalink to this heading">¶</a></h2>
<p>你想捕获一个异常后抛出另外一个不同的异常，同时还得在异常回溯中保留两个异常的信息。</p>
</section>
<section id="id3">
<h2>解决方案<a class="headerlink" href="#id3" title="Permalink to this heading">¶</a></h2>
<p>为了链接异常，使用 <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">from</span></code> 语句来代替简单的 <code class="docutils literal notranslate"><span class="pre">raise</span></code> 语句。
它会让你同时保留两个异常的信息。例如：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">example</span><span class="p">():</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>            <span class="nb">int</span><span class="p">(</span><span class="s1">&#39;N/A&#39;</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>            <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s1">&#39;A parsing error occurred&#39;</span><span class="p">)</span> <span class="kn">from</span> <span class="nn">e</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">example</span><span class="p">()</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">3</span>, in <span class="n">example</span>
<span class="gr">ValueError</span>: <span class="n">invalid literal for int() with base 10: &#39;N/A&#39;</span>
</pre></div>
</div>
<p>上面的异常是下面的异常产生的直接原因：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s2">&quot;&lt;stdin&gt;&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
  <span class="n">File</span> <span class="s2">&quot;&lt;stdin&gt;&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">5</span><span class="p">,</span> <span class="ow">in</span> <span class="n">example</span>
<span class="ne">RuntimeError</span><span class="p">:</span> <span class="n">A</span> <span class="n">parsing</span> <span class="n">error</span> <span class="n">occurred</span>
<span class="o">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>在回溯中可以看到，两个异常都被捕获。
要想捕获这样的异常，你可以使用一个简单的 <code class="docutils literal notranslate"><span class="pre">except</span></code> 语句。
不过，你还可以通过查看异常对象的 <code class="docutils literal notranslate"><span class="pre">__cause__</span></code> 属性来跟踪异常链。例如：</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">example</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">RuntimeError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;It didn&#39;t work:&quot;</span><span class="p">,</span> <span class="n">e</span><span class="p">)</span>

    <span class="k">if</span> <span class="n">e</span><span class="o">.</span><span class="n">__cause__</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Cause:&#39;</span><span class="p">,</span> <span class="n">e</span><span class="o">.</span><span class="n">__cause__</span><span class="p">)</span>
</pre></div>
</div>
<p>当在 <code class="docutils literal notranslate"><span class="pre">except</span></code> 块中又有另外的异常被抛出时会导致一个隐藏的异常链的出现。例如：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">example2</span><span class="p">():</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>            <span class="nb">int</span><span class="p">(</span><span class="s1">&#39;N/A&#39;</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>            <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Couldn&#39;t parse:&quot;</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
<span class="gp">...</span>
<span class="go">&gt;&gt;&gt;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">example2</span><span class="p">()</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">3</span>, in <span class="n">example2</span>
<span class="gr">ValueError</span>: <span class="n">invalid literal for int() with base 10: &#39;N/A&#39;</span>
</pre></div>
</div>
<p>在处理上述异常的时候，另外一个异常发生了：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s2">&quot;&lt;stdin&gt;&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
  <span class="n">File</span> <span class="s2">&quot;&lt;stdin&gt;&quot;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">5</span><span class="p">,</span> <span class="ow">in</span> <span class="n">example2</span>
<span class="ne">NameError</span><span class="p">:</span> <span class="k">global</span> <span class="n">name</span> <span class="s1">&#39;err&#39;</span> <span class="ow">is</span> <span class="ow">not</span> <span class="n">defined</span>
<span class="o">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>这个例子中，你同时获得了两个异常的信息，但是对异常的解释不同。
这时候，<code class="docutils literal notranslate"><span class="pre">NameError</span></code> 异常被作为程序最终异常被抛出，而不是位于解析异常的直接回应中。</p>
<p>如果，你想忽略掉异常链，可使用 <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">from</span> <span class="pre">None</span></code> :</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">example3</span><span class="p">():</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>            <span class="nb">int</span><span class="p">(</span><span class="s1">&#39;N/A&#39;</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
<span class="gp">... </span>            <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s1">&#39;A parsing error occurred&#39;</span><span class="p">)</span> <span class="kn">from</span> <span class="bp">None</span>
<span class="gp">...</span>
<span class="go">&gt;&gt;&gt;</span>
<span class="go">example3()</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">5</span>, in <span class="n">example3</span>
<span class="gr">RuntimeError</span>: <span class="n">A parsing error occurred</span>
<span class="go">&gt;&gt;&gt;</span>
</pre></div>
</div>
</section>
<section id="id4">
<h2>讨论<a class="headerlink" href="#id4" title="Permalink to this heading">¶</a></h2>
<p>在设计代码时，在另外一个 <code class="docutils literal notranslate"><span class="pre">except</span></code> 代码块中使用 <code class="docutils literal notranslate"><span class="pre">raise</span></code> 语句的时候你要特别小心了。
大多数情况下，这种 <code class="docutils literal notranslate"><span class="pre">raise</span></code> 语句都应该被改成 <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">from</span></code> 语句。也就是说你应该使用下面这种形式：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
   <span class="o">...</span>
<span class="k">except</span> <span class="n">SomeException</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
   <span class="k">raise</span> <span class="n">DifferentException</span><span class="p">()</span> <span class="kn">from</span> <span class="nn">e</span>
</pre></div>
</div>
<p>这样做的原因是你应该显示的将原因链接起来。
也就是说，<code class="docutils literal notranslate"><span class="pre">DifferentException</span></code> 是直接从 <code class="docutils literal notranslate"><span class="pre">SomeException</span></code> 衍生而来。
这种关系可以从回溯结果中看出来。</p>
<p>如果你像下面这样写代码，你仍然会得到一个链接异常，
不过这个并没有很清晰的说明这个异常链到底是内部异常还是某个未知的编程错误。</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
   <span class="o">...</span>
<span class="k">except</span> <span class="n">SomeException</span><span class="p">:</span>
   <span class="k">raise</span> <span class="n">DifferentException</span><span class="p">()</span>
</pre></div>
</div>
<p>当你使用 <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">from</span></code> 语句的话，就很清楚的表明抛出的是第二个异常。</p>
<p>最后一个例子中隐藏异常链信息。
尽管隐藏异常链信息不利于回溯，同时它也丢失了很多有用的调试信息。
不过万事皆平等，有时候只保留适当的信息也是很有用的。</p>
</section>
</section>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="Footer">
        <a href="p08_creating_custom_exceptions.html" class="btn btn-neutral float-left" title="14.8 创建自定义异常" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
        <a href="p10_reraising_the_last_exception.html" class="btn btn-neutral float-right" title="14.10 重新抛出被捕获的异常" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; <a href="../copyright.html">Copyright</a> 2017, 熊能.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>